<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '2-Step Verification' => '2-Stap Verificatie',
    'Are you sure you want to delete these items?' => 'Ben je zeker dat je deze items wilt verwijderen?',
    'Are you sure you want to delete this item?' => 'Ben je zeker dat je dit item wilt verwijderen?',
    'Authyid' => '',
    'Brand' => '',
    'Browser' => '',
    'Cellphone' => 'Telefoon',
    'Confirmed authentications' => 'Bevestigde apparaten',
    'Country' => 'Lant',
    'Current' => 'Huidige',
    'Device' => 'Apparaat',
    'Device Type' => 'Apparaat type',
    'Don\'t ask me for the code again for 30 days when I use this computer.' => 'Vraag me 30 dagen lang achter een code op dit apparaat.',
    'Email' => '',
    'Enter the verification code generated by your phone.' => 'Vul de verificatie code in gegenereerd van op uw toestel',
    'Expire At' => 'Verloopt op',
    'Expires' => 'Verloopt',
    'Hello' => 'Hallo',
    'Hostname' => 'Host',
    'ID' => '',
    'IP Address' => 'IP-adres',
    'IP-adres' => 'IP-adres',
    'If this activity is not your own operation, please contact your administrator.' => 'Als je dit niet zelf hebt gedaan, contacteer dan uw administrator',
    'Invalid two factor authentication code' => 'Foute code',
    'Ip' => '',
    'Ip Country' => 'Ip land',
    'Ip Org' => '',
    'Login' => '',
    'Os' => '',
    'Password' => 'Wachtwoord',
    'Register to get a token' => 'Registreer voor een token',
    'Remember Me' => 'Onthoud mij',
    'Remove all other devices' => 'Allen andere apparaten verwijderen',
    'Remove authenticated device' => 'Verwijder apparaat',
    'Send sms' => 'Verstuur sms',
    'Submit' => 'Bevestig',
    'Successful Login From New IP' => 'Met succes ingelogd van nieuw IP',
    'The requested page does not exist.' => 'De gevraagde pagina betaat niet.',
    'The system has detected that your account is logged in from an unused device.' => 'Het systeem heeft gedecteerd dat uw account is ingelogd van een ongebruikt apparaat.',
    'These devices have currently access to your account.' => 'Deze apparaten hebben momenteel toegang tot uw account.',
    'Time' => 'Tijd',
    'Token' => '',
    'Validate' => 'Valideer',
];
